<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>BangNote.Widget</AssemblyName>
    <RootNamespace>BangNote.Widget</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BangNote.Widget.Core\BangNote.Widget.Core.csproj" />
  </ItemGroup>

</Project>
